rerun:
  distances: False
  dihedrals: False
  new_descriptors: False



data_generation:
  schrodinger_path: /opt/schrodinger/suites2024-3
  main_dir: G:\Shared drives\OMO Lab\Projects\OMO Lab - Zaan Saeed\Data\Peptides #contains smiles/percents .txt
  smiles_input_file: all_peptides.smi
  names_input_file: all_names.txt
  target_input_file: all_percents.txt
  ##################################
  #conf_search_settings:
  wait_time_for_conf_search: 120
  conf_search_settings:
    CONFSEARCH_METHOD: MCMM
    FORCE_FIELD: OPLS_2005
    SOLVENT: None
    DIELECTRIC_CONSTANT: 1.0
    CHARGES_FROM: Force field
    CUTOFF: None
    MINI_METHOD: PRCG
    MAXIMUM_ITERATIONS: 2500
    CONVERGE_ON: Gradient
    CONVERGENCE_THRESHOLD: 0.05
    OUTCONFS_PER_SEARCH: 10000
    CONFSEARCH_STEPS: 1000
    CONFSEARCH_STEPS_PER_ROTATABLE: 100
    ENERGY_WINDOW: 104.6
    CONFSEARCH_TORSION_SAMPLING: Intermediate
  ##################################


  ################################## 
  # peptide specific features      #
  number_of_residues: 6            #
  ##################################
  

 







machine_learning:
  target_name: "target" # Name of the target file to be created/used
  model_name: "ElasticNet" # Name of the model to be used
  scoring_function: "custom_scorer" # Scoring function to be used
  n_iter: 100 # Number of iterations for the model training (RandomizedSearchCV)
  features_to_train_on:
  - side_chain_descriptors
  #- side_chain_descriptors
  #- BWdistances
  #- molecular_descriptors

  
  
  save_model: False # Whether to save the model after training

